"""User field for firing

Revision ID: 002389c42b4c
Revises: 7ab772bfb41f
Create Date: 2019-07-17 12:03:42.037111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002389c42b4c'
down_revision = '7ab772bfb41f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('actual', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'actual')
    # ### end Alembic commands ###
