"""Structure table

Revision ID: 09366f9b6ec8
Revises: 
Create Date: 2019-07-10 12:17:37.760094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09366f9b6ec8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structure',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lead', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('structure')
    # ### end Alembic commands ###
