"""new avatar format

Revision ID: 7ab772bfb41f
Revises: b5189388760e
Create Date: 2019-07-13 16:18:21.066400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ab772bfb41f'
down_revision = 'b5189388760e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('avatar_l', sa.String(length=64), nullable=True))
    op.add_column('user_info', sa.Column('avatar_m', sa.String(length=64), nullable=True))
    op.add_column('user_info', sa.Column('avatar_s', sa.String(length=64), nullable=True))
    op.drop_column('user_info', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('avatar', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('user_info', 'avatar_s')
    op.drop_column('user_info', 'avatar_m')
    op.drop_column('user_info', 'avatar_l')
    # ### end Alembic commands ###
