"""Update UserInfo Table

Revision ID: b5189388760e
Revises: 38d69aadb174
Create Date: 2019-07-12 11:33:37.748119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5189388760e'
down_revision = '38d69aadb174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('avatar', sa.LargeBinary(), nullable=True))
    op.add_column('user_info', sa.Column('work_unit', sa.Integer(), nullable=True))
    op.alter_column('user_info', 'info_owner',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'user_info', 'structure', ['work_unit'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_info', type_='foreignkey')
    op.alter_column('user_info', 'info_owner',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user_info', 'work_unit')
    op.drop_column('user_info', 'avatar')
    # ### end Alembic commands ###
